const Q=QuotaReceipt,$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let histories=window.QUOTA_HISTORIES||[];try{const saved=JSON.parse(localStorage.getItem('quota-history-v1')||'[]');histories.push(...saved);}catch{}let selected=histories[0]?.id;
function persist(){try{localStorage.setItem('quota-history-v1',JSON.stringify(histories.filter(x=>x.local)));}catch{$('status').textContent='Storage unavailable; export to retain history.';}}
function displayTime(ms){return new Date(ms).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function current(){return histories.find(h=>h.id===selected);}function pct(b){return b?($('metric').value==='remaining'?100-b.usedPercent:b.usedPercent):null;}
function card(name,b,last){const now=Date.now(),reset=b?.resetsAt?b.resetsAt*1000:null;let timing='Reset time not reported';if(reset)timing=reset>now?'Reported reset: '+displayTime(reset):'Reported reset passed: '+displayTime(reset)+' · refresh needed';return `<div class="card"><h2>${name}${b?.windowDurationMins?' · '+b.windowDurationMins+' min':''}</h2><div class="big">${b?pct(b).toFixed(1)+'% '+$('metric').value:'Not reported'}</div><div class="track"><div class="fill" style="width:${b?pct(b):0}%"></div></div><p class="small">${esc(timing)}</p><p class="muted small">${b?(100-b.usedPercent).toFixed(1)+'% remaining at this observation':'Unavailable is not zero use or unlimited use.'}</p></div>`;}
function chart(rows,key,start,end){const points=rows.filter(r=>r[key]);if(!points.length)return '<p class="muted">No observations for this window in the selected period.</p>';const W=980,H=230,L=44,R=20,T=15,B=35,x=t=>L+(t-start)/(end-start)*(W-L-R),y=v=>H-B-v/100*(H-T-B),percent=v=>$('metric').value==='remaining'?100-v:v;let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${key==='primary'?'Short':'Long'} window ${$('metric').value} percentage observations"><title>Provider-reported quota observations. Gaps and resets are not interpolated.</title>`;
 for(const v of [0,25,50,75,100])svg+=`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#e4e9df"/><text x="2" y="${y(v)+4}">${v}%</text>`;
 for(let i=0;i<5;i++){const t=start+(end-start)*i/4;svg+=`<text x="${x(t)}" y="${H-8}" text-anchor="${i===0?'start':i===4?'end':'middle'}">${esc(displayTime(t))}</text>`;}
 const resets=[...new Set(points.map(r=>r[key]?.resetsAt).filter(Boolean))];for(const reset of resets){const t=reset*1000;if(t>=start&&t<=end)svg+=`<line x1="${x(t)}" x2="${x(t)}" y1="${T}" y2="${H-B}" stroke="#a46735" stroke-dasharray="4 4"><title>Reported reset ${esc(displayTime(t))}</title></line>`;}
 for(const [a,b] of Q.segments(rows,key))svg+=`<path d="M${x(a.time)},${y(percent(a.usedPercent))} H${x(b.time)} V${y(percent(b.usedPercent))}" fill="none" stroke="#386b4c" stroke-width="2"/>`;
 for(const row of points){const b=row[key];svg+=`<circle cx="${x(Date.parse(row.capturedAt))}" cy="${y(percent(b.usedPercent))}" r="3" fill="#386b4c"><title>${esc(displayTime(Date.parse(row.capturedAt)))} · ${percent(b.usedPercent).toFixed(1)}% ${$('metric').value}</title></circle>`;}return svg+'</svg>';
}
function render(){const h=current();$('source').innerHTML=histories.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x.title)}</option>`).join('');if(!h)return;h.samples=Q.merge(h.samples);const last=h.samples.at(-1);if(!last){$('cards').innerHTML='<p>No observations.</p>';return;}const end=Date.parse(last.capturedAt),start=end-Number($('range').value)*3600000,rows=h.samples.filter(r=>Date.parse(r.capturedAt)>=start&&Date.parse(r.capturedAt)<=end);$('observed').textContent=`${h.demo?'SYNTHETIC DEMO · ':''}${rows.length} observations · latest ${displayTime(end)} · ${last.plan||'plan unknown'} · not live`;$('cards').innerHTML=card('Short window',last.primary,last)+card('Long window',last.secondary,last);$('shortChart').innerHTML=chart(rows,'primary',start,end);$('longChart').innerHTML=chart(rows,'secondary',start,end);$('log').innerHTML=`<table><thead><tr><th>Observed</th><th>Short used %</th><th>Long used %</th><th>Source</th></tr></thead><tbody>${rows.slice(-100).reverse().map(r=>`<tr><td>${esc(displayTime(Date.parse(r.capturedAt)))}</td><td>${r.primary?.usedPercent??'Not reported'}</td><td>${r.secondary?.usedPercent??'Not reported'}</td><td>${esc(r.source)}</td></tr>`).join('')}</tbody></table><p class="small muted">Most recent ${Math.min(rows.length,100)} observations shown. Charts and export use all observations.</p>`;}
$('source').onchange=()=>{selected=$('source').value;render();};$('range').onchange=render;$('metric').onchange=render;
$('at').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
$('manual').onsubmit=e=>{e.preventDefault();try{const primary=$('primary').value===''?null:{usedPercent:Number($('primary').value),windowDurationMins:300,resetsAt:$('primaryReset').value?Date.parse($('primaryReset').value)/1000:null},secondary=$('secondary').value===''?null:{usedPercent:Number($('secondary').value),windowDurationMins:10080,resetsAt:$('secondaryReset').value?Date.parse($('secondaryReset').value)/1000:null};if(!primary&&!secondary)throw Error('Enter at least one reported percentage.');if([primary,secondary].some(b=>b&&(b.usedPercent<0||b.usedPercent>100)))throw Error('Percentages must be between 0 and 100.');let h=histories.find(x=>x.id==='manual');if(!h){h={id:'manual',title:'My manually recorded quota',local:true,samples:[]};histories.push(h);}h.samples.push(...Q.snapshot({rateLimits:{limitId:'codex',primary,secondary}},$('at').value,'User entered from usage screen'));selected=h.id;persist();render();$('status').textContent='Observation saved locally.';}catch(e){$('status').textContent=e.message;}};
$('import').onclick=()=>$('files').click();$('files').onchange=async()=>{try{const samples=[];for(const f of $('files').files){const text=await f.text();if(f.name.endsWith('.jsonl'))samples.push(...Q.fromTraces(text.split(/\r?\n/).filter(x=>x.trim()).map(x=>JSON.parse(x))));else{const d=JSON.parse(text);if(d.schema==='quota-history-v1')samples.push(...d.samples);else if(d.capturedAt&&d.raw)samples.push(...Q.snapshot(d.raw,d.capturedAt));else throw Error('Snapshot JSON needs capturedAt and raw fields, or an exported quota history.');}}if(!samples.length)throw Error('No reported quota observations found. Tokens alone cannot reconstruct quota.');const ids=[...new Set(samples.map(s=>s.limitId))];for(const id of ids){const h={id:'import-'+Date.now()+'-'+id,title:'Imported quota · '+id,local:true,samples:samples.filter(s=>s.limitId===id)};histories.push(h);selected=h.id;}persist();render();$('status').textContent='Imported locally. No data uploaded.';}catch(e){$('status').textContent=e.message;}finally{$('files').value='';}};
$('export').onclick=()=>{const h=current();if(!h)return;const url=URL.createObjectURL(new Blob([JSON.stringify({schema:'quota-history-v1',...h},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='quota-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
