const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const elements={},listeners={},storage={};
const el=id=>elements[id]||(elements[id]={id,value:['topic','date'].includes(id)?'all':'',innerHTML:'',textContent:'',dataset:{},hidden:false,scrollTop:0,click(){},showModal(){this.open=true},close(){this.open=false},focus(){this.focused=true},querySelectorAll(){return []}});
const document={getElementById:el,addEventListener:(n,f)=>listeners[n]=f,createElement:()=>({click(){}})};
const context={document,console,localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},Blob,URL:{createObjectURL:()=>'',revokeObjectURL(){}},setTimeout:fn=>fn(),window:{print(){}},Date,Map,Set,Number,JSON,globalThis:null};context.globalThis=context;
vm.createContext(context);for(const f of ['trace-engine.js','receipt-view.js','demo-data.js'])vm.runInContext(fs.readFileSync(__dirname+'/'+f,'utf8'),context);context.RECEIPT_DATA=context.window.RECEIPT_DATA;vm.runInContext(fs.readFileSync(__dirname+'/trace-ui.js','utf8'),context);
assert.equal(el('receiptBody').hidden,true);el('vendor').value='openai';el('vendor').onchange();assert.equal(el('receiptBody').hidden,false);assert.equal((el('tasks').innerHTML.match(/class="item"/g)||[]).length,4);assert.ok(el('metrics').innerHTML.includes('42,400'));assert.ok(!el('tasks').innerHTML.includes('data-field="category"'));assert.ok(!el('tasks').innerHTML.includes('Response IDs'));assert.ok(!el('metrics').innerHTML.includes('$0.052'));
el('topic').value='lite-work';el('topic').onchange();assert.equal((el('tasks').innerHTML.match(/class="item"/g)||[]).length,2);
const key=JSON.stringify(['lite-work','lite-work-turn-0']);listeners.click({target:{closest:s=>s==='[data-rate]'?{dataset:{key,rate:'4'}}:null}});assert.ok(storage['trace-receipts-v1'].includes('"rating":4'));assert.ok(el('totals').innerHTML.includes('80.0%'));assert.ok(el('totals').innerHTML.includes('1 of 2 messages rated'));
listeners.change({target:{dataset:{key,field:'progress'},value:'Decision'}});assert.ok(storage['trace-receipts-v1'].includes('Decision'));
el('vendor').value='claude';el('vendor').onchange();assert.ok(el('metrics').innerHTML.includes('4,520'));assert.ok(el('metrics').innerHTML.includes('$0.01'));el('date').value='1900-01-01';el('date').onchange();assert.ok(el('tasks').innerHTML.includes('No messages match'));assert.ok(el('totals').innerHTML.includes('0 of 0 messages rated'));
el('vendor').value='openai';el('vendor').onchange();el('topic').value='lite-review';el('topic').onchange();assert.ok(el('metrics').innerHTML.includes('Unpriced'));assert.ok(!el('metrics').innerHTML.includes('$0.00'));
console.log('Receipt UI tests passed: vendor gate, all chats, topic/date scope, read-only labels, two-decimal money, star persistence, utility coverage, unknown prices.');

el('uploadHelpButton').onclick();assert.equal(el('uploadHelp').open,true);el('closeUploadHelp').onclick();assert.equal(el('uploadHelp').open,false);assert.equal(el('uploadHelpButton').focused,true);
(async()=>{const records=[{type:'session_meta',timestamp:'2026-10-06T12:00:00Z',payload:{id:'professor'}},{type:'turn_context',timestamp:'2026-10-06T12:00:01Z',payload:{turn_id:'pt',model:'gpt-6.1-sol'}},{type:'response_item',timestamp:'2026-10-06T12:00:02Z',payload:{type:'message',role:'user',content:[{type:'input_text',text:'Explain inventory costs'}]}},{type:'token_usage_record',timestamp:'2026-10-06T12:00:03Z',payload:{response_id:'pr',turn_id:'pt',usage:{input_tokens:20,output_tokens:10,total_tokens:30}}}];el('file').files=[{name:'professor-chat.jsonl',text:async()=>records.map(r=>JSON.stringify(r)).join('\n')}];await el('file').onchange();assert.ok(el('status').textContent.includes('Nothing was uploaded'));assert.ok(el('tasks').innerHTML.includes('Explain inventory costs'));assert.ok(el('metrics').innerHTML.includes('42,430'));console.log('Upload checks passed: help dialog opens/closes, original JSONL is imported locally and rendered.');})().catch(e=>{console.error(e);process.exitCode=1;});
