const fs=require('fs'),crypto=require('crypto'),assert=require('assert/strict'),E=require('./trace-engine'),V=require('./receipt-view'),{credentialHits}=require('./publish-data'),{policy}=require('./curate-data');
const m=JSON.parse(fs.readFileSync('data/trace-manifest.json','utf8')),ds=JSON.parse(fs.readFileSync('data/receipts.json','utf8'));assert.equal(m.datasets.length,5);
for(const d of m.datasets)for(const f of d.files){const b=fs.readFileSync(f.path);assert.equal(b.length,f.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);assert.equal(credentialHits(b.toString('utf8')),0);assert.ok(fs.existsSync('dist/'+f.path));if(f.kind==='original-trace')assert.equal(E.parseJSONL(b.toString('utf8')).length,f.records);else assert.equal(JSON.parse(b).tasks.length,ds.find(x=>x.id===d.id).tasks.length);}
assert.equal(V.scope(ds,'openai').messages,10);assert.equal(ds.reduce((n,d)=>n+d.publication.removedMessages,0),12);
for(const d of ds){const excluded=new Set(policy.excludedTasks[d.id]||[]);for(const t of d.tasks)assert.ok(!excluded.has(t.id));for(const e of d.events)assert.ok(!excluded.has(e.taskId));for(const c of d.calls)assert.ok(!excluded.has(c.taskId));for(const t of d.tasks){assert.equal(new Set(t.responseIds).size,t.responseIds.length);assert.ok(t.responseIds.every(id=>d.events.some(e=>e.id===id)));}}
for(const id of ['lite-code','lite-work','lite-review']){assert.ok(!fs.existsSync('dist/data/traces/'+id));assert.ok(ds.find(d=>d.id===id).files.every(f=>f.includes('/curated/')));}
const html=fs.readFileSync('dist/index.html','utf8');assert.ok(html.includes('src="shared-data.js"'));assert.ok(!html.includes('src="demo-data.js"'));assert.ok(html.includes('id="uploadHelp"'));assert.ok(html.includes('id="usecaseSection"'));assert.ok(html.includes('id="actionSection"'));assert.ok(!html.includes('id="usecaseSection" open'));assert.ok(!html.includes('font-size:9px'));assert.ok(html.includes('width:58vw'));assert.ok(html.includes('in the top-right corner to open the receipt.'));
for(const f of ['private-sources.json','quota-current.private.json','enrich-receipt.js','.env.local','setup-api-key.sh'])assert.ok(!fs.existsSync('dist/'+f));
assert.ok(fs.readFileSync('dist/favicon.svg','utf8').includes('🧾'));assert.ok(html.includes('href="favicon.svg"'));assert.ok(html.includes('value="claude" selected'));assert.ok(fs.existsSync('dist/demo-reflections.js'));
console.log('Shared demo checks passed: exactly 12 exclusions, 10 retained Lite messages, excluded usage removed, no downloadable raw Lite contexts, curated exports, larger type and collapsed sections.');

assert.ok(html.includes('id="receiptScroll"'));assert.ok(html.includes('.receipt-body{display:flex;flex-direction:column;flex:1;min-height:0}'));assert.ok(html.includes('.receipt-scroll{flex:1;min-height:0;overflow-y:scroll'));assert.ok(html.includes('.receipt-scroll .items{flex:none;overflow:visible'));assert.ok(html.indexOf('id="receiptScroll"')<html.indexOf('id="usecaseSection"'));assert.ok(html.includes('</section></div><footer class="totals"'));console.log('Scroll structure checks passed: expanded sections and messages share the constrained scroll area; totals stay outside.');
