const assert=require('assert/strict'),fs=require('fs'),E=require('./trace-engine');
const c=(id,out=10)=>({type:'assistant',requestId:id,message:{id:'message-'+id,model:'claude-opus-5-5',usage:{input_tokens:2,cache_read_input_tokens:100,cache_creation_input_tokens:20,cache_creation:{ephemeral_1h_input_tokens:20},output_tokens:out,output_tokens_details:{thinking_tokens:4}},content:[{type:'tool_use',id:'tool-'+id,name:'Write'}]}});
let n=E.normalize([{name:'claude',records:[{type:'user',uuid:'u',message:{content:'Build accounting app'}},c('a'),c('a',12)]}]);
assert.equal(n.events.length,1);assert.equal(n.calls.length,1);assert.equal(E.totals(n.events).total,134);assert.equal(n.events[0].output,12);
assert.ok(Math.abs(E.price(n.events[0]).low-(2*4+100*.2+20*8+12*20)/1e6)<1e-12);
let o=E.normalize([{name:'code',records:[{type:'session_meta',payload:{id:'s'}},{type:'turn_context',payload:{turn_id:'t',model:'gpt-6-astra'}},{type:'response_item',payload:{type:'message',role:'user',content:[{type:'input_text',text:'Build a prototype. Allow deleting rules.'}]}},{type:'response_item',payload:{type:'custom_tool_call',name:'exec',call_id:'x',input:'await tools.exec_command({}); await tools.apply_patch({});'}},{type:'token_usage_record',payload:{response_id:'r',turn_id:'t',usage:{input_tokens:100,cached_input_tokens:80,output_tokens:20,reasoning_output_tokens:10,total_tokens:120},thread_token_usage:{total_tokens:90000}}},{type:'token_usage_record',payload:{response_id:'r',turn_id:'t',usage:{input_tokens:100,cached_input_tokens:80,output_tokens:20,total_tokens:120}}}]}]);
assert.equal(o.events.length,1);assert.equal(o.calls.length,2);assert.equal(o.events[0].input,20);assert.equal(o.events[0].total,120);assert.equal(o.events[0].toolIds.length,2);assert.equal(o.tasks[0].category,'Build / create');assert.equal(o.duplicates,1);
assert.equal(E.cleanPrompt,undefined);assert.equal(E.intention('continue'),'Continue work');assert.equal(E.intention('too many elements, simplify the widget'),'Correction / refinement');assert.equal(E.intention('yes, venmo please'),'Back-and-forth / clarification');
assert.equal(E.price({...o.events[0],model:'unknown'}).low,null);
for(const id of ['lite-code','lite-work','boba-code','claude-work','lite-review']){
const d=require('./demo-data').find(d=>d.id===id);const sum=E.totals(d.events);assert.equal(new Set(d.events.map(e=>e.id)).size,d.events.length);assert.equal(new Set(d.calls.map(c=>c.id)).size,d.calls.length);assert.equal(d.tasks.reduce((a,t)=>a+E.totals(d.events.filter(e=>e.taskId===t.id)).total,0),sum.total);assert.equal(d.events.reduce((a,e)=>a+e.input+e.read+e.write5+e.write1+(e.unknownWrite||0)+e.output,0),sum.total);for(const e of d.events){assert.ok(d.tasks.some(t=>t.id===e.taskId));for(const c of e.toolIds)assert.ok(d.calls.some(x=>x.id===c));}}
console.log('Trace accounting tests passed: provider normalization, deduplication, cache TTL, reasoning subsets, unknown prices, task conservation, all 5 synthetic demo datasets.');

const multiDay=E.normalize([{name:'whole-thread',records:[{type:'session_meta',timestamp:'2026-09-01T00:00:00Z',payload:{id:'s'}},{type:'token_usage_record',timestamp:'2026-09-01T01:00:00Z',payload:{response_id:'early',usage:{input_tokens:10,output_tokens:2}}},{type:'token_usage_record',timestamp:'2026-10-06T20:00:00Z',payload:{response_id:'late',usage:{input_tokens:20,output_tokens:3}}}]}]);
assert.equal(multiDay.events.length,2);assert.equal(E.totals(multiDay.events).total,35);assert.equal(multiDay.coverage.start,'2026-09-01T00:00:00.000Z');assert.equal(multiDay.coverage.end,'2026-10-06T20:00:00.000Z');assert.equal(multiDay.coverage.records,3);
