const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const {calculate}=require('./receipt');
const context={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/sample.js','utf8'),context);
const sample=JSON.parse(JSON.stringify(context.window.RECEIPT_SAMPLE));
let r=calculate(sample);
assert.equal(r.total.tokens,28140);
assert.ok(Math.abs(r.total.cost-0.09132)<1e-10);
assert.equal(r.payment.paid,0);
assert.equal(r.payment.fixed,20);
assert.equal(r.groups.reduce((n,g)=>n+g.tokens,0),r.total.tokens);
assert.equal(r.requests.reduce((n,g)=>n+g.tokens,0),r.total.tokens);
const dup=structuredClone(sample);dup.events.push(dup.events[0]);assert.throws(()=>calculate(dup),/duplicate/);
const missing=structuredClone(sample);missing.events[0].usage=null;r=calculate(missing);assert.equal(r.total.unknownTokens,1);assert.equal(r.total.unknownCost,1);
const invalid=structuredClone(sample);invalid.events[0].usage.cached_input_tokens=2000;assert.throws(()=>calculate(invalid),/Cached/);
const reported=structuredClone(sample);reported.events[0].provider_cost_usd=0.7;assert.equal(calculate(reported).rows[0].cost,0.7);
const relabel=structuredClone(sample);relabel.events[0].activity='Revise';assert.equal(calculate(relabel).total.tokens,calculate(sample).total.tokens);
console.log('Passed: cached token pricing, grouping conservation, duplicate rejection, missing usage, payment separation, reported cost precedence, activity relabeling.');
