const E=TraceReceipt,V=ReceiptView;let datasets=window.RECEIPT_DATA||[],stored={};try{stored=JSON.parse(localStorage.getItem('trace-receipts-v1')||'{}');}catch{}
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Math.round(n).toLocaleString(),money=n=>'$'+n.toFixed(2);
const cost=s=>s.unknown?(s.unknown===s.responses?'Unpriced':money(s.low)+'–'+money(s.high)+' + unpriced'):money(s.high)===money(s.low)?money(s.low):money(s.low)+'–'+money(s.high);
const percent=n=>n===null?'—':n.toFixed(1)+'%';
const progressOptions=['Decision','Working artifact','Understanding','Errand / operation','Community connection','Others'],outcomeOptions=['Not assessed','Still exploring','Needs revision','Ready to use','Used / applied','Abandoned'];
const prefs=r=>stored[r.d.id]?.tasks?.[r.t.id]||{};
function save(){try{localStorage.setItem('trace-receipts-v1',JSON.stringify(stored));$('status').textContent='Reflections saved on this device.';}catch{$('status').textContent='Local storage unavailable. Export to keep your reflections.';}}
function info(text,label){return `<span class="info-wrap"><button class="info" aria-label="${esc(label)}" aria-expanded="false">?</button><span class="tip" role="tooltip">${text}</span></span>`;}
function options(list,value,placeholder){return (placeholder?`<option value="">${placeholder}</option>`:'')+list.map(s=>`<option value="${esc(s)}" ${s===value?'selected':''}>${esc(s)}</option>`).join('');}
function refreshFilters(){const vendor=$('vendor').value,old=$('topic').value;const ds=datasets.filter(d=>d.provider===vendor);$('topic').innerHTML='<option value="all">All chats</option>'+ds.map(d=>`<option value="${esc(d.id)}">${esc(d.title)}</option>`).join('');$('topic').value=ds.some(d=>d.id===old)?old:'all';refreshDates();}
function refreshDates(){const old=$('date').value,vendor=$('vendor').value,topic=$('topic').value;const ds=datasets.filter(d=>d.provider===vendor&&(topic==='all'?!d.id.includes('review'):d.id===topic));const days=[...new Set(ds.flatMap(d=>d.tasks.map(t=>V.day(t.time))).filter(Boolean))].sort().reverse();$('date').innerHTML='<option value="all">All dates</option><option value="30d">Last 30 days</option><option value="7d">Last 7 days</option><option value="3d">Last 3 days</option><option value="24h">Last 24 hours</option>'+days.map(d=>`<option value="${d}">${d}</option>`).join('');$('date').value=['all','30d','7d','3d','24h',...days].includes(old)?old:'all';}
function current(){return V.scope(datasets,$('vendor').value,$('topic').value||'all',$('date').value||'all');}
function totalsView(sc){const s=E.totals(sc.events),a=V.assess(sc.rows,prefs,E);$('totals').innerHTML=`<div class="total"><label>Total estimate cost ${info('Sum of recorded model usage × the applicable API rates for the messages shown. This is an API-equivalent scenario, not your subscription payment. Unpriced models and missing tool fees are excluded from the known subtotal.','Explain total cost')}</label><b>${sc.events.length?cost(s):'—'}</b><small>${s.unknown?`${s.unknown} responses unpriced`:'API equivalent · USD'}</small></div><div class="total"><label>Total estimate utility ${info('Usefulness index = average star rating ÷ 5 × 100. Only rated user messages count; unrated messages are missing data, not zero. This is an ordinal, subjective reflection index—not dollars, economic utility, or a validated outcome measure.','Explain utility index')}</label><b>${percent(a.utility)}</b><small>${a.rated} of ${sc.messages} messages rated</small></div><div class="total"><label>Reflection gain % ${info('A reflection score, not financial ROI: 100 × (50% usefulness + 20% progress category + 30% output status). Usefulness = stars ÷ 5. Progress: decision/artifact/community 1.0; understanding 0.8; errand 0.6; others 0.5. Output: applied 1.0; ready 0.8; revision 0.4; exploring 0.2; abandoned 0.0. All three answers are required. Total = mean of complete message scores; incomplete answers are excluded. Category weights are illustrative design assumptions, not evidence that one kind of work is intrinsically better.','Explain reflection gain')}</label><b>${percent(a.gain)}</b><small>${a.scored} of ${sc.messages} messages fully reflected</small></div>`;}
function renderItems(sc){$('tasks').innerHTML=sc.rows.map((r,i)=>{const {d,t}=r,p=prefs(r),s=E.totals(r.events),rating=V.rating(p),g=V.reflectionGain(p),dt=new Date(t.time),stamp=Number.isFinite(+dt)?dt.toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Date unavailable';return `<article class="item" data-key="${esc(r.key)}"><div class="item-meta">${String(i+1).padStart(2,'0')} / ${esc(d.title)} · ${esc(stamp)} ${r.isMessage?'':'· background activity'}</div><div class="item-head"><button class="prompt-button" data-expand="${esc(r.key)}" aria-expanded="false" aria-label="Expand full user message">${esc(t.prompt)}</button><span class="tag" title="${esc(t.categorySource||'Local keyword inference')}">${esc(t.category)}</span></div><div class="prompt-full" data-full="${esc(r.key)}" hidden>${esc(t.prompt)}</div><div class="item-metrics"><div><b>${num(s.total)}</b><span>Recorded tokens</span></div><div><b>${r.events.length?cost(s):'—'}</b><span>API estimate</span></div><div><b>${s.responses}</b><span>Model responses</span></div><div><b>${r.calls.length}</b><span>Tool calls</span></div></div><p class="summary">${esc(V.summary(r))} <span class="summary-source">${t.summarySource?.startsWith('LLM')?'Mini-model summary':'Local trace summary'}</span></p>${r.isMessage?`<div class="reflection"><div><label>Was the result useful?</label><div class="stars" role="group" aria-label="Usefulness rating">${[1,2,3,4,5].map(n=>`<button class="star ${rating>=n?'active':''}" data-rate="${n}" data-key="${esc(r.key)}" aria-label="Rate ${n} of 5 stars" aria-pressed="${rating===n}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01Z"/></svg></button>`).join('')}</div></div><div><label>What moved forward?</label><select data-key="${esc(r.key)}" data-field="progress" aria-label="What this message moved forward">${options(progressOptions,p.progress,'Choose…')}</select></div><div><label>What happened to the output?</label><select data-key="${esc(r.key)}" data-field="outcome" aria-label="What happened to this output">${options(outcomeOptions,p.outcome||'Not assessed')}</select></div></div><div class="value-line"><span data-utility="${esc(r.key)}">Usefulness: <strong>${rating?percent(rating/5*100):'—'}</strong></span><span data-gain="${esc(r.key)}">Reflection gain: <strong>${percent(g)}</strong></span></div>`:''}</article>`;}).join('')||'<div class="empty">No messages match this vendor, chat and date.<br>Try All chats / All dates.</div>';}
function render(){const vendor=$('vendor').value,on=!!vendor;$('gate').hidden=on;$('receiptBody').hidden=!on;$('topic').disabled=!on;$('date').disabled=!on;$('dataNotice').textContent=window.RECEIPT_SHARED?'Shared sample traces are hosted with this app. Files you select are processed locally in your browser.':datasets.every(d=>d.subtitle?.includes('Synthetic'))?'Demo data. Upload your own trace to see your actual activity.':'Local trace data. Files stay on this device unless you explicitly run optional model enrichment.';if(!on)return;
 const sc=current(),s=E.totals(sc.events);$('coverage').textContent=`${$('date').value==='all'?(window.RECEIPT_SHARED?'Curated shared history':'Full imported history'):'Filtered by message date'} · ${sc.sets.reduce((n,d)=>n+d.files.length,0)} files · ${sc.rows.length} entries · dates in your local timezone`;const dates=sc.rows.map(r=>V.day(r.t.time)).filter(Boolean).sort();if(dates.length)$('coverage').textContent+=` · ${dates[0]} – ${dates[dates.length-1]}`;
 $('metrics').innerHTML=[['Recorded tokens',num(s.total)],['API-equivalent estimate',s.responses?cost(s):'—'],['User requests',num(sc.messages)],['Tool activity',num(sc.calls.length)]].map(([label,v])=>`<div class="metric"><label>${label}</label><b>${v}</b></div>`).join('');
 const groups={};for(const r of sc.rows){const c=r.t.category,g=groups[c]||(groups[c]={events:[],messages:0});g.events.push(...r.events);if(r.isMessage)g.messages++;}const groupRows=Object.entries(groups).map(([c,g])=>({c,...g,s:E.totals(g.events)})).sort((a,b)=>b.s.total-a.s.total);$('usecases').innerHTML=`<table class="usecase-table"><thead><tr><th>Use case / token share</th><th>Cost share</th><th>Messages</th><th>Cost / msg</th><th>Total cost</th></tr></thead><tbody>${groupRows.map(g=>{const share=s.total?g.s.total/s.total*100:0,cp=g.messages?{...g.s,low:g.s.low/g.messages,high:g.s.high/g.messages}:null;return `<tr><td><div class="share-label"><span>${esc(g.c)}</span><span>${percent(share)}</span></div><div class="track"><div class="fill" style="width:${share}%"></div></div></td><td>${s.unknown||g.s.unknown||!s.low?'—':percent(g.s.low/s.low*100)}</td><td>${g.messages}</td><td>${cp?cost(cp):'—'}</td><td>${g.s.responses?cost(g.s):'—'}</td></tr>`;}).join('')||'<tr><td colspan="5">No measured requests</td></tr>'}</tbody></table>`;
 const models=[...new Set(sc.events.map(e=>e.model))],colors=['#4287f5','#ffd500','#ff87d7','#4287f580','#ffa126','#52e3d9'];$('modelBar').innerHTML=models.map((m,i)=>{const ms=E.totals(sc.events.filter(e=>e.model===m)),share=s.total?ms.total/s.total*100:100/models.length;return `<button class="model-segment" style="width:${share}%;background:${colors[i%colors.length]}" aria-label="${esc(m)}: ${num(ms.total)} tokens" title="${esc(m)}"><span class="tip" role="tooltip"><strong>${esc(m)}</strong><ul><li>${num(ms.responses)} responses</li><li>${num(ms.total)} tokens</li><li>${cost(ms)} API estimate</li></ul></span></button>`;}).join('');
 const acts={};for(const c of sc.calls)(acts[c.action]||(acts[c.action]=[])).push(c);$('actions').innerHTML=Object.entries(acts).map(([name,cs])=>`<span class="action">${esc(name)}<b>${cs.length}</b></span>`).join('')||'<small>No recorded tools</small>';
 $('actionTable').innerHTML=`<table><thead><tr><th>Action</th><th>Calls</th><th>Associated tokens</th><th>Associated estimate</th></tr></thead><tbody>${Object.entries(acts).map(([name,cs])=>{const ids=new Set(cs.map(c=>c.id)),sum=E.totals(sc.events.filter(e=>e.toolIds.some(id=>ids.has(id))));return `<tr><td>${esc(name)}</td><td>${cs.length}</td><td>${sum.responses?num(sum.total):'Unlinked'}</td><td>${sum.responses?cost(sum):'—'}</td></tr>`;}).join('')}</tbody></table>`;
 $('messageCount').textContent=`${sc.messages} messages · scroll ↓`;
 $('sourceNotes').innerHTML=sc.sets.map(d=>`<p><strong>${esc(d.title)}</strong><br>${esc(d.coverage?.start?.slice(0,10)||'Start not recorded')} – ${esc(d.coverage?.end?.slice(0,10)||'End not recorded')} UTC<br>Refreshed ${esc(d.importedAt?.slice(0,16).replace('T',' '))} UTC<br>${d.duplicates||0} duplicate usage records removed; ${d.invalid||0} skipped.${d.enrichment?'<br>Mini-model analysis: '+esc(d.enrichment.model)+', '+num(d.enrichment.inputTokens+d.enrichment.outputTokens)+' additional tokens. Analysis is separate from original trace costs.':''}</p>${d.files.map(f=>`<p>${window.RECEIPT_SHARED&&/^data\/(?:traces\/[a-z0-9-]+\/[A-Za-z0-9_.-]+\.jsonl|curated\/[a-z0-9-]+\.receipt\.json)$/.test(f)?`<a href="${esc(f)}" download>${esc(f.split('/').pop())} ↓</a>`:esc(f)}</p>`).join('')}`).join('')+'<p>The shared demo omits only the owner-selected message entries and their usage. New uploads are imported in full. Date filters select whole message/turn entries. Automatic review activity is a separate topic and excluded from All chats.</p>';
 renderItems(sc);totalsView(sc);
}
function findRow(key){return current().rows.find(r=>r.key===key);}
function setPref(key,field,value){const r=findRow(key);if(!r)return;const p=stored[r.d.id]||(stored[r.d.id]={tasks:{}});p.tasks=p.tasks||{};(p.tasks[r.t.id]||(p.tasks[r.t.id]={}))[field]=value;save();}
document.addEventListener('click',e=>{const star=e.target.closest('[data-rate]');if(star){const row=findRow(star.dataset.key);if(!row)return;const next=V.rating(prefs(row))===Number(star.dataset.rate)?null:Number(star.dataset.rate);setPref(row.key,'rating',next);if(next===null)setPref(row.key,'value','Not assessed');const scroll=$('tasks').scrollTop;renderItems(current());$('tasks').scrollTop=scroll;totalsView(current());return;}const expand=e.target.closest('[data-expand]');if(expand){const entry=expand.closest('.item'),full=entry.querySelector('.prompt-full');full.hidden=!full.hidden;expand.setAttribute('aria-expanded',String(!full.hidden));return;}const button=e.target.closest('.info');if(button){const wrap=button.closest('.info-wrap'),open=wrap.classList.toggle('open');button.setAttribute('aria-expanded',String(open));}});
document.addEventListener('change',e=>{const el=e.target;if(!el.dataset.field)return;setPref(el.dataset.key,el.dataset.field,el.value);const r=findRow(el.dataset.key),line=el.closest?.('.item')?.querySelector('[data-gain]');if(line&&r)line.innerHTML=`Reflection gain: <strong>${percent(V.reflectionGain(prefs(r)))}</strong>`;totalsView(current());});
$('vendor').onchange=()=>{ $('topic').value='all';$('date').value='all';refreshFilters();render();};$('topic').onchange=()=>{refreshDates();render();};$('date').onchange=render;
$('importButton').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const files=Array.from($('file').files);if(!files.length)return;const incoming=[];if(files.length===1&&files[0].name.endsWith('.json')){const p=JSON.parse(await files[0].text());if(p.schema==='ai-receipt-enrichment-v1'){const d=datasets.find(d=>d.id===p.datasetId);if(!d)throw Error('Upload the corresponding receipt first.');for(const t of d.tasks){const a=p.tasks.find(a=>a.id===t.id);if(a&&E.CATEGORIES.includes(a.category)&&typeof a.summary==='string'){t.category=a.category;t.categorySource='LLM · '+p.model;t.aiSummary=a.summary.slice(0,1200);t.summarySource='LLM · '+p.model;}}d.enrichment=p.usage;refreshFilters();render();$('status').textContent='Mini-model labels and summaries imported.';return;}if(p.schema==='ai-receipt-stack-v1'){incoming.push(...p.datasets);stored={...stored,...p.reflections};}else if(p.schema==='ai-receipt-trace-v1')incoming.push(p);else throw Error('Use a receipt JSON or raw JSONL trace.');}else{const groups={};for(const f of files){const records=E.parseJSONL(await f.text()),provider=records.some(r=>r.type==='session_meta'||r.type==='token_usage_record')?'openai':'claude';(groups[provider]||(groups[provider]=[])).push({name:f.name,records});}for(const fs of Object.values(groups)){const d=E.normalize(fs,fs[0].name.replace(/\.jsonl$/,''));d.id='import-'+d.provider+'-'+Date.now();d.subtitle='Imported locally';incoming.push(d);}}
 for(const d of incoming){if(d.schema!=='ai-receipt-trace-v1'||!Array.isArray(d.tasks)||!Array.isArray(d.events)||!Array.isArray(d.calls)||!Array.isArray(d.files))throw Error('Invalid receipt structure.');if(d.reflections)stored[d.id]=d.reflections;const i=datasets.findIndex(x=>x.id===d.id);if(i>=0)datasets[i]=d;else datasets.push(d);}if(incoming.length){$('vendor').value=incoming[0].provider;$('topic').value='all';$('date').value='all';}refreshFilters();render();save();$('status').textContent=incoming.length&&incoming.every(d=>!d.events.length)?'Files read locally, but no supported response-level usage records were found. Token costs cannot be calculated from this format. Nothing was uploaded.':'Imported full files locally. Nothing was uploaded to a server.';}catch(e){$('status').textContent=e.message;}finally{$('file').value='';}};
$('exportButton').onclick=()=>{const payload={schema:'ai-receipt-stack-v1',datasets,reflections:stored},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='ai-receipt-stack.receipt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('printButton').onclick=()=>window.print();
refreshFilters();render();

$('uploadHelpButton').onclick=()=>$('uploadHelp').showModal();$('closeUploadHelp').onclick=()=>{$('uploadHelp').close();$('uploadHelpButton').focus();};
